### ISSUE TITLE
recent releases are missing on the site

### ISSUE THREAD

**Issue by oshanz** [boombatower/tumbleweed-review#18]
![image](https://user-images.githubusercontent.com/5364479/126253021-c114b3af-edbd-4391-860d-6bc6160391f4.png)

as you can see in here, according to the site latest snapshot is 20210712. 
however tumbleweed cli list more recent releases.

![image](https://user-images.githubusercontent.com/5364479/126253153-898176dc-2125-4717-b2ab-7459bc3476e9.png)

**Comment by boombatower** [comment]
Yeah, I reported the issue in #opensuse-admin IRC channel, but never received a response. Not sure if it's me or openSUSE.

```
$ ./src/main.py mail -s 2017-12
git-sync: Preparing. Repo in .git /root/.cache/tumbleweed-review/tumbleweed-review-site
git-sync: Mode sync
git-sync: Using origin/master
git-sync: Fetching from origin/master
Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
From github.com:boombatower/tumbleweed-review-site
 * branch              master     -> FETCH_HEAD
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
git-sync: In sync, all fine.
[I] ingest 2021-07
Traceback (most recent call last):
  File "./src/main.py", line 74, in <module>
    ret = args.func(args)
  File "/srv/src/mail.py", line 317, in argparse_main
    main(args.logger, cache_dir, args.start_month, output_dir, not args.no_refresh)
  File "/srv/src/mail.py", line 298, in main
    mbox_paths = mboxes_download(cache_dir, start_month, refresh)
  File "/srv/src/mail.py", line 91, in mboxes_download
    shutil.copyfileobj(mbox_gzip, mbox_file)
  File "/usr/lib64/python3.6/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/lib64/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib64/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib64/python3.6/gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

The URL being downloaded works in a browser for me and I have not explored any further

> https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/export/factory@lists.opensuse.org-2021-07.mbox.gz?start=2021-07-01&end=2021-08-01

Started occurring `Jul 14, 2021 11:05am CDT`. Any thoughts would be helpful.

**Comment by boombatower** [comment]
Perhaps it would be useful for me to expose my CI setup so anyone could see when things are not working and why.

**Comment by boombatower** [comment]
Appears to be a real bug on mailing list site.

    curl 'https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/export/factory@lists.opensuse.org-2021-07.mbox.gz?start=2021-07-01&end=2021-08-01' --output 2021-07.gz

Results in a mailbox file ending with:

> Any feedback (code re

From an email with the subject `New package: python-keyring-keyutils`

My email client shows that email last line as the following.

> Any feedback (code reviews, bug reports etc.) is always welcome!:)

With a signature and referenced URLs afterwards.

For whatever reason curl and browser do not complain about the file ending early, but the problem appears to be genuine. This should be fixed upstream by mailing list host/software, but I could also add error checking to process the partial file.

**Comment by boombatower** [comment]
Created https://progress.opensuse.org/issues/95756

**Comment by alexandru-m-g** [comment]
I don't know if this is related or relevant but the graphs from here https://metrics.opensuse.org/d/osrt_release/osrt-release?orgId=1 also end on 2021-07-12

**Comment by boombatower** [comment]
Those graphs ingest data from the review site, so yes related.

**Comment by temporarium** [comment]
Waiting patiently for your excellent service to be up and running again...

Anything others can do to help get it moving?

**Comment by boombatower** [comment]
Resolve the progress.opensuse.org issue covering the data corruption from the mailing list server. I could add an exception handler to keep processing, but then it would be presenting partial information which I think is worse. As soon as the p.o.o issue is resolve the CI run should update the site.

**Comment by boombatower** [comment]
Added a link to this bug on the review site.

**Comment by temporarium** [comment]
> Added a link to this bug on the review site.

Saw the link yesterday. Don't see it anymore. Does that mean it shall soon be back in operation?

**Comment by alexandru-m-g** [comment]
Any timeframe from opensuse about fixing the mailing list ? I have my work computer on Tumbleweed (I know, not advisable but was working great in connection with the https://review.tumbleweed.boombatower.com/ service ).

**Comment by boombatower** [comment]
No update on progress.opensuse.org issue in regard to mailing list fix.

**Comment by cgoetzke** [comment]
Didn't you have a problem with the mailing list archives omitting information a while back? And didn't it take the openSUSE folks a good while to get that fixed?

Given this issue has been sitting untouched by openSUSE for 26 days now, I'm not holding my breath for a fix.

Honestly, it almost feels like someone at openSUSE is hostile to this project, and I can't for the life of me figure out why.

**Comment by temporarium** [comment]
https://openqa.opensuse.org/ appears stuck as well... Maybe they're all on vacation.

**Comment by boombatower** [comment]
Yes, and bugzilla before that. Apparently openSUSE infra team could use help.

**Comment by thorgrin** [comment]
This might be related to https://gitlab.com/mailman/hyperkitty/-/issues/383 fixed by https://gitlab.com/mailman/hyperkitty/-/merge_requests/347
However, if this is the case, the already imported messages would need to be reimported to enable the download again.

The problem probably happened at 14.7.2021 since https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/export/factory@lists.opensuse.org-2021-07.mbox.gz?start=2021-07-01&end=2021-07-13 works as expected, but https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/export/factory@lists.opensuse.org-2021-07.mbox.gz?start=2021-07-14&end=2021-08-01 returns only a 10 byte long file. Continuing from 15.7.2021, everything is fine again.

Therefore, a temporary workaround can probably be implemented to download on a daily basis and just skip (and report) the broken days.

**Comment by JoeSalmeri** [comment]
>> Therefore, a temporary workaround can probably be implemented to download on a daily basis and just skip (and
>> report) the broken days

That seems like a great idea...flag the days where a problem exists with "bad data" or something like that and then continue to calculate for days where the problem does not exist.

I am surprised that this issue has been broken now for 6 or 7 weeks.

**Comment by physxP** [comment]
Is there any other way of getting the stability info?  I need to change snapshot on my work PC to more stable version.

**Comment by ericjs** [comment]
FWIW in experimenting with these urls the 2021-07-1 to 2021-08-01 one that Throgrin posted reliably downloads an empty mbox file (in a 10 byte gzip), the 2021-07-01 to 2021-07-13 one he posted seems to reliably download a complete mbox file. The original 2021-07-14 to 2021-08-01 one from boombatower behaves _non-deterministically_. Each time I try it it truncates the mbox file in a slightly different place, and at least once I managed to get one that didn't seem to be truncated (or perhaps it was just not noticeably so).

**Comment by ericjs** [comment]
> Is there any other way of getting the stability info? I need to change snapshot on my work PC to more stable version.

How about requesting archives via the mail interface itself?

**Comment by ericjs** [comment]
Is the syntax of that export URL documented anywhere?

**Comment by boombatower** [comment]
> Is the syntax of that export URL documented anywhere?

I believe someone told me the params in discord so not sure.

Feel free to submit a PR, but rather busy right now.

My main concern with skipping day data is we have no way in the display to indicate days are being skipped which means we could skip right over problem threads. If someone wants to implement the day ingest (for the month of issue and beyond) I'll try and review.

**Comment by thorgrin** [comment]
> My main concern with skipping day data is we have no way in the display to indicate days are being skipped which means we could skip right over problem threads. If someone wants to implement the day ingest (for the month of issue and beyond) I'll try and review.

I believe that the problem was fixed in the hyperkitty and should be available in the next release, according to their changelog. Therefore, it should solve itself in the future.

I guess that It's better to have incomplete information than none - right now I'm updating my tumbleweed distros to the latest release and just hoping for the best.

Maybe, we could just ignore that and continue with August, as that month seems to download fine again?

**Comment by boombatower** [comment]
```
[I] ingest 2021-10
Traceback (most recent call last):
  File "./src/main.py", line 74, in <module>
    ret = args.func(args)
  File "/srv/src/mail.py", line 322, in argparse_main
    main(args.logger, cache_dir, args.start_month, output_dir, not args.no_refresh)
  File "/srv/src/mail.py", line 303, in main
    mbox_paths = mboxes_download(cache_dir, start_month, refresh)
  File "/srv/src/mail.py", line 96, in mboxes_download
    shutil.copyfileobj(mbox_gzip, mbox_file)
  File "/usr/lib64/python3.6/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/lib64/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib64/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib64/python3.6/gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

Apparently, very much not fixed on openSUSE list.

**Comment by ericjs** [comment]
Definitely still a problem. FWIW, the gzip is not getting truncated but rather the .mbox file within, which is why curl and the browser don't complain. Even date ranges that appear to work seem to suffer the same problem but (I would guess) get lucky with only harmless whitespace being truncated. If I do multiple downloads (with curl _or_ browser) with the same date range and look at the size in bytes of the resultant file, that size is different every time, even with ranges that _appear_ to produce a complete file.

**Comment by ericjs** [comment]
BTW is there any way to draw attention to the bug? I've posted my observations there, and while I know nothing about the code involved, the sort of behavior I described should surely make it obvious where to look in the code for the problem.

**Comment by tneo** [comment]
@boombatower the ticket contains a potential solution. Have you tried that? Is it possible to use https://openqa.opensuse.org/ for the quality rating, based upon the amount of tests passed or not

**Comment by JoeSalmeri** [comment]
@tneo 

That's the method I have been using to determine which build to update to since this problem appears to be stuck in limbo.

It has worked out well for me.

**Comment by temporarium** [comment]
> @tneo
> 
> That's the method I have been using to determine which build to update to since this problem appears to be stuck in limbo.
> 
> It has worked out well for me.

Same here. I only update to builds with low failure rates. So far, so good.

**Comment by boombatower** [comment]
Since this was mentioned recently I decided to revive things and see if the mailing list is fixed...

> [I] ingest 2023-07
> ...
> EOFError: Compressed file ended before the end-of-stream marker was reached

Huge progress, much bug.

**Comment by digitaltrails** [comment]
Would it be feasible/workable to just the mailing list and procmail (or similar) arriving mail it to a local archive?

Recently Tumbleweed has sent more papercuts my way than usual.  Some kind of quality metric is sorely missed.
